// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloServer.proto

package myproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("helloServer.proto", fileDescriptor_a038b2eef6c1cfff) }

var fileDescriptor_a038b2eef6c1cfff = []byte{
	// 47 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0x2d, 0x2e,
	0x31, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xad, 0x04, 0x33, 0x92, 0xd8, 0xc0,
	0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x28, 0x39, 0xc9, 0xa1, 0x1e, 0x00, 0x00, 0x00,
}
